"""baseline schema

Revision ID: d328e7296a01
Revises: 
Create Date: 2026-08-28 11:38:38.167860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd328e7296a01'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('state', sa.Enum('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', name='jobstate'), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('progress', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_state'), ['state'], unique=False)

    op.create_table('programme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_th', sa.String(length=300), nullable=False),
    sa.Column('name_en', sa.String(length=300), nullable=True),
    sa.Column('university', sa.String(length=200), nullable=False),
    sa.Column('year_be', sa.Integer(), nullable=True),
    sa.Column('source_filename', sa.String(length=500), nullable=False),
    sa.Column('source_pages', sa.Integer(), nullable=True),
    sa.Column('extraction_method', sa.Enum('NATIVE', 'REPAIRED', 'VISION', name='extractionmethod'), nullable=False),
    sa.Column('mark_rate', sa.Float(), nullable=True),
    sa.Column('integrity_report', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('university', 'name_th', 'year_be', name='uq_programme_identity')
    )
    op.create_table('analysis_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('programme_id', sa.Integer(), nullable=False),
    sa.Column('career_slug', sa.String(length=120), nullable=False),
    sa.Column('snapshot_date', sa.String(length=10), nullable=False),
    sa.Column('extraction_model', sa.String(length=200), nullable=True),
    sa.Column('embedding_model', sa.String(length=200), nullable=True),
    sa.Column('links_reviewed', sa.Boolean(), nullable=False),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['programme_id'], ['programme.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_run_programme_id'), ['programme_id'], unique=False)

    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('programme_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('title_th', sa.String(length=300), nullable=False),
    sa.Column('title_en', sa.String(length=300), nullable=True),
    sa.Column('credits', sa.Float(), nullable=True),
    sa.Column('credit_spec', sa.String(length=40), nullable=True),
    sa.Column('category', sa.Enum('GENERAL_EDUCATION', 'CORE', 'MAJOR_REQUIRED', 'MAJOR_ELECTIVE', 'FREE_ELECTIVE', 'UNKNOWN', name='coursecategory'), nullable=False),
    sa.Column('year_of_study', sa.Integer(), nullable=True),
    sa.Column('description_th', sa.Text(), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('clos', sa.JSON(), nullable=True),
    sa.Column('responsibility_map', sa.JSON(), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('linked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['programme_id'], ['programme.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('programme_id', 'code', name='uq_course_code')
    )
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_programme_id'), ['programme_id'], unique=False)

    op.create_table('course_skill_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.String(length=40), nullable=False),
    sa.Column('snapshot_date', sa.String(length=10), nullable=False),
    sa.Column('level_ordinal', sa.Integer(), nullable=True),
    sa.Column('level_sources', sa.JSON(), nullable=True),
    sa.Column('evidence_span', sa.Text(), nullable=True),
    sa.Column('evidence_channel', sa.String(length=10), nullable=True),
    sa.Column('retrieval_rank', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('channels_agree', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('PROPOSED', 'ACCEPTED', 'REJECTED', 'LEVEL_ADJUSTED', name='linkstatus'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('level_ordinal IS NULL OR level_ordinal BETWEEN 0 AND 2', name='ck_level_ordinal_range'),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'skill_id', name='uq_course_skill')
    )
    with op.batch_alter_table('course_skill_link', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_skill_link_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_skill_link_skill_id'), ['skill_id'], unique=False)
        batch_op.create_index('ix_link_status', ['status'], unique=False)

    op.create_table('out_of_vocabulary_skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('term', sa.String(length=300), nullable=False),
    sa.Column('evidence_span', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('out_of_vocabulary_skill', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_out_of_vocabulary_skill_course_id'), ['course_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('out_of_vocabulary_skill', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_out_of_vocabulary_skill_course_id'))

    op.drop_table('out_of_vocabulary_skill')
    with op.batch_alter_table('course_skill_link', schema=None) as batch_op:
        batch_op.drop_index('ix_link_status')
        batch_op.drop_index(batch_op.f('ix_course_skill_link_skill_id'))
        batch_op.drop_index(batch_op.f('ix_course_skill_link_course_id'))

    op.drop_table('course_skill_link')
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_programme_id'))

    op.drop_table('course')
    with op.batch_alter_table('analysis_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_run_programme_id'))

    op.drop_table('analysis_run')
    op.drop_table('programme')
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_state'))
        batch_op.drop_index(batch_op.f('ix_job_kind'))

    op.drop_table('job')
    # ### end Alembic commands ###
