"""record inference provider on analysis_run

Revision ID: e9b5ac388d53
Revises: d328e7296a01
Create Date: 2026-08-28 12:02:11.604187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9b5ac388d53'
down_revision: Union[str, Sequence[str], None] = 'd328e7296a01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_run', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider', sa.Enum('LOCAL', 'WORKERS_AI', name='modelprovider'), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_run', schema=None) as batch_op:
        batch_op.drop_column('provider')

    # ### end Alembic commands ###
